#!/usr/bin/sh
echo "Build all"

cargo fmt --all
cargo update && cargo upgrade
cargo build && cargo build --release && cargo build --target=x86_64-unknown-linux-gnu && cargo build --target=x86_64-unknown-linux-gnu --release
