[package]
authors = ["dheijl <danny.heijl@telenet.be>"]
edition = "2018"
name = "swyh-rs"
version = "0.9.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "*"
bitflags = "*"
chrono = "*"
cpal = {git = "https://github.com/rustaudio/cpal"}
crossbeam-channel = "*"
dirs = "*"
fltk = "*" 
htmlescape = "*"
lazy_static = "*"
log = {version = "*", features = ["max_level_trace", "release_max_level_debug"]}
rust-ini = "*"
simplelog = "*"
strfmt = "*"
stringreader = "*"
tiny_http = "*"
ureq = {version = "*", features = ["charset"]}
url = "*"
xml-rs = "*"
[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winuser", "std"]}
[target.'cfg(unix)'.dependencies]
libc = "^0.2"
