[package]
name = "swyh-rs"
version = "0.8.8"
authors = ["dheijl <danny.heijl@telenet.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { git = "https://github.com/moalyousef/fltk-rs", features = ["fltk-bundled"]}
cpal = { git = "https://github.com/dheijl/cpal" }
tiny_http = "*"
ascii = "*"
crossbeam-channel = "*"
lazy_static = "*"
url = "*"
ureq = { version = "*", features = ["charset"] }
xml-rs = "*"
stringreader = "*"
strfmt = "*"
htmlescape = "*"
chrono = "*"
bitflags = "*"
rust-ini = "*"
dirs = "*"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "std"] }
[target.'cfg(unix)'.dependencies]
libc = "^0.2"