[package]
name = "swyh-rs"
version = "0.7.3"
authors = ["dheijl <danny.heijl@telenet.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "*", features = ["fltk-bundled"] }
cpal = { path="X:\\Documents\\GitHub\\cpal\\" }
tiny_http = "*"
ascii = "*"
crossbeam-channel = "*"
lazy_static = "*"
url = "*"
ureq = { version = "*", features = ["charset"] }
xml-rs = "*"
stringreader = "*"
strfmt = "*"
htmlescape = "*"
chrono = "*"
bitflags = "*"
