[package]
resolver = "2"
authors = ["dheijl <danny.heijl@telenet.be>"]
edition = "2018"
name = "swyh-rs"
version = "1.3.20"
description = "Stream What You Hear written in Rust"
license = "MIT"
repository = "https://github.com/dheijl/swyh-rs/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[dependencies]
bitflags = "1.2.1"
chrono = "0.4.19"
cpal = "0.13.4"
crossbeam-channel = "0.5.1"
dirs = "3.0.2"
fltk = { version = "1.1.10", features = ["use-ninja"] }
htmlescape = "0.3.1"
ifcfg = "0.1.2"
lazy_static = "1.4.0"
log = { version = "0.4.14", features = ["max_level_trace", "release_max_level_debug", "serde"] }
parking_lot = "0.11.1"
serde = { version = "1.0.127", features = ["derive"] }
simplelog = "0.10.0"
strfmt = "0.1.6"
stringreader = "0.1.1"
tiny_http = "0.8.2"
toml = "0.5.8"
ureq = { version = "2.1.1", features = ["charset"] }
url = "2.2.2"
xml-rs = "0.8.4"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "std"] }
winres = "0.1.11"
[target.'cfg(unix)'.dependencies]
libc = "0.2.98"

[patch.crates-io]
#fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
#tiny_http = { git = "https://github.com/tiny-http/tiny-http" }
#cpal = { git = "https://github.com/RustAudio/cpal" }
