[package]
authors = ["dheijl <danny.heijl@telenet.be>"]
edition = "2018"
name = "swyh-rs"
version = "1.3.10"
description = "Stream What You Hear written in Rust"
license = "MIT"
repository = "https://github.com/dheijl/swyh-rs/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[dependencies]
bitflags = "1.2.1"
chrono = "0.4.19"
cpal = "0.13.2"
crossbeam-channel = "0.5.0"
dirs = "3.0.1"
fltk = { version = "0.15.14", features = ["use-ninja"] }
htmlescape = "0.3.1"
lazy_static = "1.4.0"
log = { version = "0.4.14", features = ["max_level_trace", "release_max_level_debug"] }
parking_lot = "0.11.1"
rust-ini = "0.16.1"
simplelog = "0.9.0"
strfmt = "0.1.6"
stringreader = "0.1.1"
tiny_http = "0.8.0"
ureq = { version = "2.0.2", features = ["charset"] }
url = "2.2.1"
xml-rs = "0.8.3"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "std"] }
winres = "0.1.11"
[target.'cfg(unix)'.dependencies]
libc = "0.2.90"

[patch.crates-io]
#tiny_http = { git = "https://github.com/tiny-http/tiny-http" }
